name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Packages
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Start cache local server
        id: local-server
        run: |
          node turbo-server.js &
          echo "::set-output name=LOCAL_TURBO_SERVER_PID::$!"
      - name: work
        run: | 
          echo "${{ steps.local-server.outputs.LOCAL_TURBO_SERVER_PID }}"
          curl "http://127.0.0.1:9080/v8/artifacts/bla"
          sleep 5
          kill "${{ steps.local-server.outputs.LOCAL_TURBO_SERVER_PID }}"
        

