name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Packages
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Start cache local server
        run: |
          node turbo-server.js &
          export LOCAL_TURBO_SERVER_PID=$!
          echo "::set-env name=LOCAL_TURBO_SERVER_PID::$LOCAL_TURBO_SERVER_PID"
      - name: work
        run: | 
          echo "$LOCAL_TURBO_SERVER_PID"
          curl "http://127.0.0.1:9008/v8/artifacts/bla"
          sleep 5
          kill "$LOCAL_TURBO_SERVER_PID"
        

