name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Packages
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Start cache local server
        run: |
          node turbo-server.js &
          export TURBO_SERVER_PID=$!
      - name: work
        run: | 
          echo "$TURBO_SERVER_PID"
          sleep 5
          kill "$TURBO_SERVER_PID"
        

